on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [oxlint, oxfmt, build, test]
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: mise run install --frozen-lockfile

      - name: Cache Playwright Browsers
        id: playwright-cache
        if: ${{ matrix.task == 'test' }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Playwright Browsers
        if: ${{ matrix.task == 'test' && steps.playwright-cache.outputs.cache-hit != 'true' }}
        run: pnpm exec playwright install --with-deps chromium
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0

      - run: mise run ${{ matrix.task }}
